name: Release Workflow

on:
  workflow_dispatch:
    # This event allows manual triggering
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for .NET Framework projects

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-version: '16.0'  # Adjust to the version your project requires

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild /p:Configuration=Release

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: List contents of p2pconn/bin/Release
      run: ls -R p2pconn/bin/Release

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets
        asset_path: .p2pconn/bin/Release/p2p.exe  # Update this path
        asset_name: p2p.exe  # Update this name
        asset_content_type: application/octet-stream
