name: Build and Attach to Release

on:
  release:
    types:
      - created

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest  # Use a Windows runner for .NET Framework projects

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-version: '16.0'  # Adjust to the version your project requires

    - name: Restore NuGet packages
      run: nuget restore p2pconn.sln

    - name: Build
      run: msbuild p2pconn.sln /p:Configuration=Release

    - name: ILMerge
      run: |
        nuget install ilmerge -Version 3.0.41 -OutputDirectory ./ilmerge
        ls -R ./
        ./ilmerge/ILMerge.3.0.41/tools/net452/ILMerge.exe /out:p2p-portable.exe ./bin/Release/p2p.exe ./bin/Release/*.dll
        move p2p-portable.exe .\bin\Release\
        

    - name: List contents of p2pconn/bin/Release
      run: ls -R ./

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: p2pconn/bin/Release/*.exe
