name: Build and Attach to Release

on:
  workflow_dispatch:
    # This event allows manual triggering
  release:
    types:
      - created

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest  # Use a Windows runner for .NET Framework projects

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
