name: Build and Attach to Release

on:
  workflow_dispatch:
    # This event allows manual triggering
  release:
    types:
      - created

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest  # Use a Windows runner for .NET Framework projects

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-version: '16.0'  # Adjust to the version your project requires

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: List contents of p2pconn/bin/Release
      run: ls -R p2pconn/bin/Release

    - name: Get latest release tag
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: p2pconn/bin/Release/p2p.exe
        tag_name: ${{ env.LATEST_TAG }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: p2pconn/bin/Release/p2p.exe
        tag_name: ${{ steps.get-latest-tag.outputs.tag }}
